# Dockerfile
FROM maven:3.9.6-jdk-17-slim AS build
WORKDIR /app
  
COPY pom.xml .
  
COPY src ./src
 
RUN mvn clean package -DskipTests
  
FROM openjdk:17-jre-alpine
ARG JAR_FILE=target/jwt-demo-0.0.1.jar
  
COPY --from=build /app/${JAR_FILE} /app/app.jar
  
USER 1000:1000
  
EXPOSE 8080
  
ENTRYPOINT ["java", "-jar", "/app/app.jar"]